import offstage from "@/assets/images/OffStage/offstage";
import CulturalFest from '../../assets/visualassets/CulturalFest.js';

const OffStageDetails = [
  {
    eventName: "Rangoli",
    facultyCoordinator:
      "Ms Srinisha AP/CE(My Campus Clubs)",
    facultyNumber: "8870815415",
    studentCoordinator: "HEMADEVI K, AKSHAYA M ",
    studentNumber: "7094323056, 9003691193",
    venue: "Boys hostel – E block road",
    time: "11:00AM",
    description: [
      "Rangoli art should be of 5ft X 5ft",
      "Maximum time for Duo is 30 minutes while maximum time for Solo will be 1 hour.",
      "All required materials should be brought by the participants themselves.",
      "Usage of salt other than suji colours and flowers should be avoided",
      "Use of phones, tablets or printouts as a preference will lead to immediate disqualification.",
      "Evaluation will be based on theme, colour combinations, creativity and clarity of rangoli",
    ],
    image: CulturalFest.offstage.Rangoli,
    reverse: false,
  },
  {
    eventName: "Face Painting",
    facultyCoordinator:
      "Ms.Diviya AP/CD(My Campus Clubs)",
    facultyNumber: "9715571117",
    studentCoordinator: "A.GOWSIKA, K.HARIHARAN ",
    studentNumber: "8870027551, 9585168861",
    venue: "A BLOCK",
    time: "11:00AM",
    description: [
      "The team must have 2 members- the one who paints and the other whose face is to be painted",
      "All the required materials must be brought by the participants.",
      "Time limit for face painting is 1 hour.",
      "Theme will be given on the spot",
      "Use of phones, tablets or printouts as a preference will lead to immediate disqualification.",
      "Participants will be judged on the basis of creativity, innovation and design.",
    ],
    image: CulturalFest.offstage.FacePainting,
    reverse: true,
  },
  {
    eventName: "Mehandi",
    facultyCoordinator:
      "Dr.J .Rehaboth Nissi AP/ SH(My Campus Clubs)",
    facultyNumber: "7892765172",
    studentCoordinator: "ANUSHA B, SANGAVI M ",
    studentNumber: "86101 09739, 8754052949",
    venue: "A-Block",
    time: "12:00PM",
    description: [
      "Participants must bring their own materials.",
      "Participants have to apply mehandi on the palmer as well as the dorsal side of the hand",
      "Participants can apply mehandi on their own hand or any other person’s hand",
      "If you are applying for other person, you have to bring that person. ",
      "The Time limit will be 1 hour.",
      "Judging will be based on neatness and creativity.",
    ],
    image: CulturalFest.offstage.Meganthi,
    reverse: false,
  },
  {
    eventName: "Reels",
    facultyCoordinator:
      "Mr. Sivaji Rao, AP/CSD(Photography Club)",
    facultyNumber: "+91 90437 84314",
    studentCoordinator: "S.Karthikeyan, BharaniRaj",
    studentNumber: "7639273091, 63797 95076",
    venue: "C Block",
    time: "10:00AM",
    description: [
      "Minimum time limit: 15 seconds",
      "Maximum time limit: 30 seconds",
      "Participants should act and present their own video to the audience.",
      "The videos will be displayed on screen at the event, and the winners will be chosen",
    ],
    image: CulturalFest.offstage.Reels,
    reverse: true,
  },
  {
    eventName: "Short Film",
    facultyCoordinator:
      "Ms. Gopika, AP/MBA(Nature and yoga club)",
    facultyNumber: "",
    studentCoordinator: "A.K.Dhanush Kumar, M.S.Giridharan",
    studentNumber: "8428486830, 9788951601",
    venue: "B-Block",
    time: "11:00AM",
    description: [
      "Topics : THE ETHICAL DELIMMA, OCIAL COMMENTARY, FAMILY DYNAMICS, OWN CONTENT",
      	"Duration:5-7 Mins.",
      "Abusive Languages Should Not Be Used. ",
      "Last Date for Submission: 11.03.2025",
      "Mail id: druva25shortfilm@gmail.com",
      "Two Members Can Register for One Film.",
      "If Any Violation the Team Will Be Disqualified.",
    ],
    image: CulturalFest.offstage.Shortfilm,
    reverse: false,
  },
  {
    eventName: "Photography",
    facultyCoordinator:
      "Dr.C.Arul  Murugan, Mr.Varatharajan N",
    facultyNumber: "+91 81221 07125",
    studentCoordinator: "Mr.Gowtham P, Mr.Balamurugan G",
    studentNumber: "+91 97892 88677, +91 88258 88205",
    venue: "C-Block",
    time: "10:00AM",
    description: [
      "Mobile and DSLR photography are allowed (DSLR- recommended)",
      "Theme will be given on-spot.",
      "The participant has to capture 3 photographs on the theme announced on the spot by the judges",
      "Each participant is allowed to submit one picture taken at the given spot",
      "All photographs must be original. No watermark or editing is allowed",
      "Device used to take picture must be mentioned along with your details",
      "Digital images are evaluated on the basis of (I) IMPACT, (II) COMPOSITION. (III) TECHNICAL QUALITY, and (IV) SUITABILITY for the specific theme",
      "The additional instructions will be announced on the spot.",
    ],
    image: CulturalFest.offstage.Photography,
    reverse: true,
  },
  {
    eventName: "Fireless Cooking",
    facultyCoordinator: "Dr. A. Kavitha,AP/SHMy Campus Clubs)",
    facultyNumber: "+91 99651 44560",
    studentCoordinator: "Dhanasri K,Nisha K",
    studentNumber: "7373556352,7010885872",
    venue: "A-Block",
    time: "1:00PM",
    description: [
      "2 members in a team",
      "Total preparation must be 35-40 minutes",
      "Participants must exhibit a chart with the name of food and ingredients used to prepare it",
      "Participants could prepare numerous dishes in the stipulated time",
      "Participants must bring the required cooking items (NOTE: only working table will be provided)",
      "Only vegetarian dishes are allowed to cook",
      "The Cutting of vegetables/fruits should be done on the spot",
      "Participants are allowed to bring non-electric equipment (mixer, chopper, juicer, grater etc.,)",
      "Evaluation will be based on table cleanliness, presentation and taste of the food",
    ],
    image: CulturalFest.offstage.Fireless,
    reverse: false,
  },
  {
    eventName: "Vegetable Carving",
    facultyCoordinator:
      "Ms. Vidhya Lakshmi, AP/EEE(My Campus Clubs)",
    facultyNumber: "+91 95979 01377",
    studentCoordinator: "Abishek, Selva Bharathi",
    studentNumber: "9344763457, 9360670633",
    venue: "B – Block",
    time: "12:00PM",
    description: [
      "All contestants are required to produce one sculpture that are made entirely of fruits/ vegetables.",
      "No flowers other than those sculpted of fruits/vegetables are allowed.",
      "The contestant will have one hour to complete the piece for judging.",
      "All pieces are to be made of entirely edible food. No plastic supports in frames.",
      "Added colors are acceptable.",
      "Extra emphasis will be placed on the use of the natural shapes and colours of the fruit/vegetables and how they are used to support and enhance each other.",
      "All tools including hand tools like chisels, knives, saws, drills, angle cutters, shaped Cutters, power drimmels, other power tools like squares, levels are acceptable",
      "No pre preparation of vegetables or fruits before competition is allowed",
      "Participants should not take the help of others to complete the task.",
    ],
    image: CulturalFest.offstage.VegetableCraving,
    reverse: true,
  },
  {
    eventName: "Nail Art",
    facultyCoordinator:
      "Dr.B.P.Sreeja ,AP /IT(My Campus Clubs)",
    facultyNumber: "+91 82206 12234",
    studentCoordinator: "Naveena K, Harini M",
    studentNumber: "9345838151, 9342773207",
    venue: "C – Block",
    time: "12 PM",
    description: [
      "Competitors must bring their own tools and products",
      "No mobile phones, tablets or smart watches during the competition for both the competitor and the model.",
      "No outside communication with competitors while competitions are going on.",
      "Competitors allowed to prepare the natural nail prior to the competition. But absolutely no application work of any kind until the competition officially begins.",
      "Complete one hand with gel polish on natural nails. No extensions. Three pink and white French manicure style nails and two nails a flat crème red.",
      "Competitors using a model will have 30 minutes to complete one hand.",
      "Competitors working on themselves will receive 5 extra minutes.",
    ],
    image: CulturalFest.offstage.NailArt,
    reverse: false,
  },
  {
    eventName: "Craft Art",
    facultyCoordinator:
      "Ms. Kavithamani, AP/EEE(Arts and Crafts Club)",
    facultyNumber: "",
    studentCoordinator: "Swetha S, AADHITH KRISHNA S",
    studentNumber: "63805 28337, 9384396343",
    venue: "A – Block",
    time: "12 PM",
    description: [
      "No mobile phones, tablets or smart watches during the competition for both the competitor and the model.",
      "No outside communication with competitors while competitions are going on.",
      "Competitors are not allowed to prepare the craft prior to the competition. And absolutely no application work of any kind until the competition officially begins.",
      "Competitors are allowed to use water colors, paper, cardboard and necessary materials have to be brought by themselves.",
      "Competitors will have 30 minutes to complete the craft.",
      "Final results will be decided by the allocated judges.",
    ],
    image: CulturalFest.offstage.CarftArt,
    reverse: true,
  },
];

export default OffStageDetails;
